### PR TITLE
Parse metrics from stats file

### PR DESCRIPTION
**Pull request by roclark**

### CODE REVIEW

**Comment by roclark** [comment]
Not completely finished yet, but I wanted to see if you had any feedback/suggestions while I am in the middle of the implementation. So far, I am able to get 8 new metrics (all that I am planning on including from this file at the moment), but I have the following items left to complete:

- [ ] Get rid of magic-numbers on lines 168-180
- [ ] Add help text for all metrics within the stats file

**Comment by roclark** [comment]
FYI: I added a commit which includes help text for the new metrics, but I haven't been able to fully test and format it, so this is still a WIP. If, however, the tests pass and it doesn't need to be formatted further, this will be the final update. I will update once I get more info.

**Comment by roclark** [comment]
All formatted and tested and looks good to me! Ready to merge whenever you are.

**Comment by roclark** [comment]
Putting this on hold again. I believe I found a way to retrieve the same metrics for the MGS/MDS nodes. I will play around with that and see if it is feasible or not and let you know what I find.

**Comment by roclark** [comment]
Nevermind, looks like the stats files on the MGS/MDS nodes does not contain the same metrics. Good to go once again.

**Comment by joehandzik** [comment]
LGTM

**Pull request merged**
